import type { Metadata } from "next";

import NavMenu from "@/components/NavMenu";
import { Providers } from "@/redux/provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body >
        <Providers>
          <main>
            <NavMenu />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
